### ISSUE TITLE
BitMono.GUI not work 

### ISSUE THREAD

**Issue by tabs** [sunnamed434/BitMono#129]
### BitMono Version

error MSB4166: 子节点“2”过早退出。正在关闭。可以在“C:\Users\yys\AppData\Local\Temp\MSBuildTempcyq\”中的文件中找到诊断信息

### .NET Version

无

### Description

我clone了项目，但是VS2022编译BitMono.API时候。报错了，error MSB4166: 子节点“2”过早退出。正在关闭。可以在“C:\Users\yys\AppData\Local\Temp\MSBuildTempcyq\”中的文件中找到诊断信息,这是为什么.

UNHANDLED EXCEPTIONS FROM PROCESS 30932:
=====================
2023-05-22 11:09:44
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Microsoft.Build.Collections.RetrievableEntryHashSet`1.AddEvenIfPresent(T value)
   在 Microsoft.Build.Collections.RetrievableEntryHashSet`1.System.Collections.Generic.IDictionary<System.String,T>.set_Item(String name, T value)
   在 Microsoft.Build.BackEnd.BinaryTranslator.BinaryReadTranslator.TranslateDictionary[D,T](D& dictionary, ObjectTranslator`1 objectTranslator, NodePacketCollectionCreator`1 dictionaryCreator)
   在 Microsoft.Build.Execution.ProjectInstance.TranslateTargets(ITranslator translator)
   在 Microsoft.Build.Execution.ProjectInstance.TranslateAllState(ITranslator translator)
   在 Microsoft.Build.Execution.ProjectInstance.FactoryForDeserialization(ITranslator translator)
   在 Microsoft.Build.BackEnd.TranslatorHelpers.Translate[T](ITranslator translator, T& instance, NodePacketValueFactory`1 valueFactory)
   在 Microsoft.Build.BackEnd.BuildRequestConfiguration.Translate(ITranslator translator)
   在 Microsoft.Build.BackEnd.BuildRequestConfiguration.FactoryForDeserialization(ITranslator translator)
   在 Microsoft.Build.BackEnd.NodePacketFactory.PacketFactoryRecord.DeserializeAndRoutePacket(Int32 nodeId, ITranslator translator)
   在 Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, ITranslator translator)
   在 Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by sunnamed434** [comment]
BitMono.GUI not working yet, it requires total refactoring and rewriting using new BitMono Engine API

**Comment by tabs** [comment]
> BitMono.GUI not working yet, it requires total refactoring and rewriting using the new BitMono Engine API

"Okay, please continue to improve it as you have time. It's a great project, and I'm looking forward to it. If there's a chance, I'll donate."

**Comment by sunnamed434** [comment]
> > BitMono.GUI not working yet, it requires total refactoring and rewriting using the new BitMono Engine API
> 
> "Okay, please continue to improve it as you have time. It's a great project, and I'm looking forward to it. If there's a chance, I'll donate."

Thanks for the pleasant words, will do my best to improve the project. Thanks again, but no need to donate, also

**Comment by sunnamed434** [comment]
GUI version is removed from the project now
