### ISSUE TITLE
how to build 

### ISSUE THREAD

**Issue by x-cod3r** [sunnamed434/BitMono#140]
alot of issues while building 
add some instructions

**Comment by sunnamed434** [comment]
Hey, build only BitMono.CLI since the GUI version is unstable now and may cause errors, will add the instructions on days

**Comment by sunnamed434** [comment]
Hey, you can read the build info [here](https://github.com/sunnamed434/BitMono/blob/dev/build.md)

**Comment by sunnamed434** [comment]
Closing it, if you still have any questions about building the solution let me know. The build info is updated btw, [see here](https://github.com/sunnamed434/BitMono/blob/main/build.md)
