### ISSUE TITLE
How to use that with unity game dll

### ISSUE THREAD

**Issue by RoxDevvv** [sunnamed434/BitMono#142]
am trying to use that in my unity game dll but it says `Module Target Framework: unknown`

**Comment by sunnamed434** [comment]
Hey!

Do you get any other exceptions/errors while obfuscation? The output file work fine after obfuscation?

Send me your .dll file to my email, I'll gonna check it: [sunnamed434@proton.me](mailto:sunnamed434@proton.me)
or if this is not security-critical for you, then send it right here

**Comment by sunnamed434** [comment]
In simple words just protect Assembly-CSharp.dll, if this is old Unity then Assembly Firsrpass or smth like that l

**Comment by sunnamed434** [comment]
Closing it due to no answer, feel free to reopen this, let me know
