### ISSUE TITLE
Protection-Tests

### ISSUE THREAD

**Issue by sunnamed434** [sunnamed434/BitMono#16]
Seems as Unit-Tests or something like that but for protections

### The problem: 
How to understand that protection is working fine and it works under Mono without issues, how to automate this?

Current ways:
* Run standalone that running on Mono;
* Use Unity;
* Use dnSpy Unity Debugger;
* Use .NET Framework Console app for simple tests when there is no need to run on Mono.
* VirusTotal checks should be green :)

**Comment by StevenKrahforst** [comment]
What maybe work (ig?) is to write a little program which obfuscate an example mod for a game and then move it to the game mods folder and check if any exceptions related to BitMono have been thrown (by taking the stdout or checking the game log files)

**Comment by sunnamed434** [comment]
> What maybe work (ig?) is to write a little program which obfuscate an example mod for a game and then move it to the game mods folder and check if any exceptions related to BitMono have been thrown (by taking the stdout or checking the game log files)

Could be a good one

**Comment by sunnamed434** [comment]
I asked a question on [stackoverflow](https://stackoverflow.com/questions/74631823/how-to-test-obfuscated-app-which-runs-via-unity), I already got an interesting question, but still, I'm waiting for something else and then I will start working on it

**Comment by sunnamed434** [comment]
I asked a question on [stackoverflow](https://stackoverflow.com/questions/74631823/how-to-test-obfuscated-app-which-runs-via-unity), I already got an interesting question, but still, I'm waiting for something else and then I will start working on it

**Comment by sunnamed434** [comment]
The best way I found is: 

1. Install the needed eg [unity 2020.3.0](https://unity.com/releases/editor/whats-new/2020.3.0)
2. Unity\Editor\Data\MonoBleedingEdge\bin\mono.exe
3. Copy the \bin directory to BitMono
4. Do the project for tests that run BitMono engine and protect file into the memory then writes in the file and executes mono.exe with the obfuscated .DLL

The only thing is that possible to check if there are no BadImageException or other weird exceptions and initialize only from Module cctor and Main

**Comment by sunnamed434** [comment]
Get the runtime mono version (useful in future tests):
```cs
System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription
```
OR
```cs
 Type type = Type.GetType("Mono.Runtime");
 if (type != null)
 {                                          
     MethodInfo displayName = type.GetMethod("GetDisplayName", BindingFlags.NonPublic | BindingFlags.Static);
     if (displayName != null)                   
         Debug.Log(displayName.Invoke(null, null)); 
 }
```

**Comment by sunnamed434** [comment]
Use PEVerify

**Comment by sunnamed434** [comment]
Maybe in future will be made, but now I don't see a reason for that, too much complex and it anyway won't test it as a real person would test, closing it
