### ISSUE TITLE
CreateDelegate fails on Linux with "Parameter count mismatch"

### ISSUE THREAD

**Issue by snovvcrash** [sunnamed434/BitMono#160]
When trying to run on Linux (tested on Kali 2022.4, Ubuntu 22.04.3 LTS), BitMono.Utilities fails at `CreateDelegate` [here](https://github.com/sunnamed434/BitMono/blob/3cd079b073f69ad7f47c745d6bb4de5bdf338971/src/BitMono.Utilities/Runtime/RuntimeUtilities.cs#L24).

![1](https://github.com/sunnamed434/BitMono/assets/23141800/24821950-1df8-49d8-a9b6-c6e165d2bdfb)

If I recompile the project omitting the following `if` block, everything seems fine:

```csharp
if (hasMono)
{
    var displayName = monoType.GetMethod(KnownMonoRuntimes.GetDisplayName, BindingFlags.NonPublic | BindingFlags.Static);
    if (displayName != null)
    {
        var displayNameDelegate = (Func<string>)displayName.CreateDelegate(typeof(Func<string>), monoType);
        monoDisplayName = displayNameDelegate.Invoke();
    }
}
```

Tested with Mono 6.12.0.200 and 6.8.0.105 (crashes on both).

**Comment by sunnamed434** [comment]
Hi, nice catch, If you want you can make PR (if you do, don't forget to use the `dev` branch)

**Comment by snovvcrash** [comment]
@sunnamed434 Nah, afraid not, I've just commented the whole code block, may be there's a better solution?

**Comment by sunnamed434** [comment]
It can be done this way :

```cs
monoDisplayName = (string)displayNameMethod.Invoke(null, null);
```
