### ISSUE TITLE
Unity android app wont function after any obfuscation 

### ISSUE THREAD

**Issue by Suppzs** [sunnamed434/BitMono#163]
Hey, I have some problems with obfuscating assembly-csharp on Android builds, pc ones seem to work just fine though! When I obfuscate the assembly-csharp.dll with any function other than bitmono it just won't start. I mean unity will load the scene and etc but there will be no any signs of script functioning, like if there weren't any. Bitmono seems to not bring up any errors when obfuscating too

**Comment by sunnamed434** [comment]
Hey, which protections you have used, any which Unity version is it?

**Comment by sunnamed434** [comment]
In Unity 2021.* BitMono and BitDotNet won't work, will work on Unity 2020.* and earlier versions only
