### ISSUE TITLE
Can not run ActiveX dll after BitMono crypted.

### ISSUE THREAD

**Issue by Zeki-Gursoy** [sunnamed434/BitMono#171]
I wrote Net FW 4.8.1 dll and create TLB. Dll can not load in Excel VBA. I get "Automation error". Trying 32 and 64 bits.

**Comment by sunnamed434** [comment]
Hi, can you send the `Protections.json` file, and the logs you got from BitMono

**Comment by Zeki-Gursoy** [comment]
Of course... I attached.
.
[bitmono-2024-05-09-22-02-45.log](https://github.com/sunnamed434/BitMono/files/15273413/bitmono-2024-05-09-22-02-45.log)

[protections.json](https://github.com/sunnamed434/BitMono/files/15273418/protections.json)

**Comment by sunnamed434** [comment]
```console
[2024-05-09 22:02:47 WRN][BitMono.Obfuscation.Notifiers.ProtectionsRuntimeMonikerNotifier] [!!!] UnmanagedString - Intended for .NET Core runtime
[2024-05-09 22:02:47 WRN][BitMono.Obfuscation.Notifiers.ProtectionsRuntimeMonikerNotifier] [!!!] UnmanagedString - Intended for .NET Framework runtime
[2024-05-09 22:02:47 WRN][BitMono.Obfuscation.Notifiers.ProtectionsRuntimeMonikerNotifier] [!!!] AntiDecompiler - Intended for Mono runtime
[2024-05-09 22:02:47 WRN][BitMono.Obfuscation.Notifiers.ProtectionsRuntimeMonikerNotifier] [!!!] BitDotNet - Intended for Mono runtime
[2024-05-09 22:02:47 WRN][BitMono.Obfuscation.Notifiers.ProtectionsRuntimeMonikerNotifier] [!!!] BitMono - Intended for Mono runtime
```

First of, when you see `Intended for <...> runtime` its means specific feature is only able to work on the provided runtime. By this I mean probably this is why your `.dll` can't be used normally, I'd recommend to disable next features: AntiDecompiler, BitDotNet, and BitMono.

But, to ensure it work fine, keep only `AntiILdasm` feature as single enabled feature in `protections.json` and try to repeat the same thing you did before and let me know if it work or not

**Comment by Zeki-Gursoy** [comment]
I tried all protection options one by one.
My dll code not work in VBA below options:

1. NoNamespaces
2. FullRenamer
3. DotNetHook
4. BitMethodDotnet
5. BitDotNet
6. BitMono

**Comment by sunnamed434** [comment]
Ok. Try to do [this] (https://github.com/sunnamed434/BitMono/blob/main/troubleshooting.md#L11)

**Comment by Zeki-Gursoy** [comment]
I tried...

- BitMono App still Dll converting to 32 bit.
- I set "2.FullRenamer" and recompiled dll. "Automation Error" message still go on in VBA. If without this option works but, dll readable with ILSPY.

Have you idea?

**Comment by sunnamed434** [comment]
1. Ok, I'll try to make a fix
2. Can you enable only AntiIldasm feature, and let me know if it work

**Comment by sunnamed434** [comment]
Nice that it work. I guess `FullRenamer` was breaking smth in your code

**Comment by sunnamed434** [comment]
Try to use CallToCalli, it should work fine and hide some code

**Comment by sunnamed434** [comment]
Closing it for now, if you still experience problems with it let me know I'll reopen this
