### ISSUE TITLE
Something went wrong! System.BadImageFormatException

### ISSUE THREAD

**Issue by Arrestwarrant** [sunnamed434/BitMono#203]
Hey man sorry to borther wondering if you could help me out. I'm getting an error which I braindead cant resolve.
![Screenshot 2024-09-18 213428](https://github.com/user-attachments/assets/ec8a419f-a5fe-43e5-bf1b-103abb1f2ac4)
and thats how my folder looks like should be alright i think:
```
obfuscatingTest
├──WinFormsApp1.exe
├──WinFormsApp1.pdb
├──WinFormsApp1.runtimeconfig.json
├───libs
    ├─Newtonsoft.Json.dll
    ├─sni.dll
    ├─and 34 more
```
My project is in net8.0-windows and i use: `BitMono-v0.25.3+e64e54d3-CLI-net8.0-win-x64.zip`

I would really appreciate some help.

**Comment by sunnamed434** [comment]
Hey.

Your file is compiled in a way which cannot be protected (native compilation), it's a feature from latest dotnet versions, idk if its can be disabled, however, as I know there should be a dll file with the same name as your exe file, which has c# code, that can be read and protected, if there's no such file it means you need to search how to disable that native protection, or able to create the dll file with code.

**Comment by sunnamed434** [comment]
Hey,

Nice to hear that. It makes sense to add that info somewhere, even in BitMono when that kind of error occurs.

**Comment by sunnamed434** [comment]
Hey,

The latest release now includes information about how to deal with ReadyToRun apps.

For now, closing it, if you still need help let me know, and I'll reopen this.
