### ISSUE TITLE
Maybe a list of protections for unity

### ISSUE THREAD

**Issue by Fuckhead-Gaming-HD** [sunnamed434/BitMono#205]

**Comment by Fuckhead-Gaming-HD** [comment]
> Hi,
> 
> Yeah, make sense, but where do you think this list should be? In docs, or readme, or somewhere else? 

I think the docs would be good ,maybe list all the protections for Unity mono.

**Comment by sunnamed434** [comment]
Ok, great, that make sense, will do in next release

**Comment by sunnamed434** [comment]
@Fuckhead-Gaming-HD 

Hi, here's the list of [protections for Unity](https://bitmono.readthedocs.io/en/latest/protection-list/unity.html)

**Comment by sunnamed434** [comment]
Closing it, as the protection list was added to the docs, feel free to let me know I'll reopen.
