### ISSUE TITLE
CLI window instantly closes after specifying file.

### ISSUE THREAD

**Issue by robaxa** [sunnamed434/BitMono#31]
Hi, am I doing something wrong? After running the CLI and specifying the file the window instantly closes with no message or logfile.
Also is this only usable on dll's or also for dotnet .exe files?

**Comment by sunnamed434** [comment]
Hi,

Did you tried to drag-and-dropp the file into BitMono.CLI and creating 'libs' directory in the same path where`s your file located, try to attach logs from BitMono.CLI path if they are exist

**Comment by robaxa** [comment]
Hi, yes I also tried drag & drop, it shows correct path.  so that part works.
I can see no logs unfortunately.

By running a mono shell i can manually launch the program through it but maybe I am misunderstanding?
The architecture is client locally that connects to web server and downloads different packages depending on situation. Most of the stuff is however done serverside so maybe we should just focus on running a simpler renamer and properly rely on the webservice for security.

**Comment by sunnamed434** [comment]
Hi, today I will upload new version that probably will reveal the problem

**Comment by sunnamed434** [comment]
So, now you could try it with a new [update](https://github.com/sunnamed434/BitMono/releases/tag/v0.3.1-alpha.6)

**Comment by sunnamed434** [comment]
> same thing, is there supposed to be a logfile being created?

Now there is should outputted logs directly in Console (if you will get an error) after running the BitMono.CLI

Could you please explain steps what you are doing while obfuscating

**Comment by robaxa** [comment]
so i publish a client from my visual studio -> .exe file 
i open bitmonocli.exe 
drag and drop client.exe
filepath is established, press enter. window closes.
![image](https://user-images.githubusercontent.com/112929573/202224194-8bc123b9-b2f9-4e2f-bae2-0723f50324cf.png)

**Comment by sunnamed434** [comment]
Try this steps:

1. Your directory with `Client.exe` + as well there is should be created `libs` directory - drop there your libraries (dependencies) that you are using in your project.
2. Drag-and-drop `Client.exe` in BitMono.CLI

**Comment by sunnamed434** [comment]
Try this [update](https://github.com/sunnamed434/BitMono/releases/tag/v0.3.2-alpha.7)

**Comment by robaxa** [comment]
hmm I'm not sure it utilizes any libs in that sense, it's pretty much stand-alone.  (Once compiled). it accesses a programdata folder for settings and storage of downloads.
progress!

```
Something went wrong! System.BadImageFormatException: .NET data directory RVA is 0
   at dnlib.DotNet.MD.MetadataFactory.Create(IPEImage peImage, CLRRuntimeReaderKind runtime, Boolean verify)
   at dnlib.DotNet.MD.MetadataFactory.Load(Byte[] data, CLRRuntimeReaderKind runtime)
   at dnlib.DotNet.ModuleDefMD.Load(Byte[] data, ModuleCreationOptions options)
   at BitMono.Obfuscation.ModuleDefMDCreator.<CreateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BitMono.Obfuscation.BitMonoEngine.<ObfuscateAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Program.<Main>d__3.MoveNext()
```

**Comment by sunnamed434** [comment]
Uhmm.. seems you already protected your app and your trying to load the same file which is already obfuscated isnt it? May be Im wrong.

**Comment by robaxa** [comment]
oh hang on i will try publish a fresh version.

**Comment by sunnamed434** [comment]
Which version of .NET your app use? Seems to .NET Core, idk why `.NET data directory RVA is 0`, probably it is a matter of you or other obfuscation tool?

**Comment by robaxa** [comment]
.net 6.0 windows, nah i get same result on a "new" client

**Comment by sunnamed434** [comment]
As far as I know .NET 6.0 compiles an Native assembly (in this case you don`t need any obfuscation, because your code in native, no one decompiler could even open it in human-readable code) as well as managed - you have to use managed one via obfuscation

**Comment by sunnamed434** [comment]
> Hmm seems I need to do some more research as to why we needed to obfuscate our project haha, thanks for your time and support however!

Glad that I help you, no problem!
