### ISSUE TITLE
System.BadImageFormatException: Invalid DOS signature

### ISSUE THREAD

**Issue by StevenKrahforst** [sunnamed434/BitMono#45]
```cs
[2022-12-10 03:33:20 INF][BitMono.Obfuscation.BitMonoEngine] Loaded Module [REDACTED]
[2022-12-10 03:33:20 WRN][BitMono.Obfuscation.ProtectionsExecutionNotifier] Skip protections: AntiAssemblyEditing, FieldsHiding, NoNamespaces, ControlFlow, HideMethods, NullInstanceMethodCall, Tests, InvalidMetadata
[2022-12-10 03:33:20 INF][BitMono.Obfuscation.ProtectionsExecutionNotifier] Execute protections: AntiILdasm, AntiDe4dot, ObjectReturnType, FullRenamer, AntiDebugBreakpoints, StringsEncryption, DotNetHook, CallToCalli, BitMethodDotnet, BitDotNet
[2022-12-10 03:33:20 INF][BitMono.Obfuscation.ProtectionsExecutionNotifier] Execute only at the end: CallToCalli, BitMethodDotnet, BitDotNet
[2022-12-10 03:33:20 INF][BitMono.Obfuscation.BitMonoEngine] Preparing to protect module: [REDACTED]
Something went wrong! System.BadImageFormatException: Invalid DOS signature
   bei dnlib.PE.ImageDosHeader..ctor(DataReader& reader, Boolean verify)
   bei dnlib.PE.PEInfo..ctor(DataReader& reader, Boolean verify)
   bei dnlib.PE.PEImage..ctor(DataReaderFactory dataReaderFactory, ImageLayout imageLayout, Boolean verify)
   bei dnlib.DotNet.MD.MetadataFactory.Load(Byte[] data, CLRRuntimeReaderKind runtime)
   bei dnlib.DotNet.ModuleDefMD.Load(Byte[] data, ModuleCreationOptions options)
   bei dnlib.DotNet.AssemblyDef.Load(Byte[] data, ModuleCreationOptions options)
   bei BitMono.Core.Protecting.Resolvers.BitMonoAssemblyResolver.ResolveAsync(CancellationToken cancellationToken)
   bei BitMono.Obfuscation.BitMonoObfuscator.<StartAsync>d__7.MoveNext()
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei BitMono.Obfuscation.BitMonoEngine.<ObfuscateAsync>d__6.MoveNext()
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Program.<Main>d__2.MoveNext()
```

Happens on every DLL for a Unity Game (Beat Saber) with either .NET Framework 4.7.2 or .NET Framework 4.8

**Comment by StevenKrahforst** [comment]
I guess it fails to load one of the Game Assemblies from the Managed Directory (which I copied into the libs folder)

**Comment by sunnamed434** [comment]
Perhaps I was a little hasty with the bug label, but, looks like the module that you're trying to protect has a dead DOS signature and dnlib doesn't like it, if you are able to do that you can pin your module as a file unless it harms your safety or send it to my mail ([sunnamed434@proton.me](mailto:sunnamed434@proton.me)) then I will check what's wrong with that. As I can see in dnlib sources it checks the first 2 bytes of the loading module it is MZ, which means your module doesn't even have it.

Probably Unity Game (Beat Saber) have their custom protection which removes MZ and I think this is not the only thing that they're removing.

**Comment by StevenKrahforst** [comment]
What would be good though to see which DLL causes the throw of that Exception

**Comment by StevenKrahforst** [comment]
It's actually not the DLL I want to obfuscate, it's one of the Managed game files, just deleted a bunch of unnecessary and it worked

**Comment by sunnamed434** [comment]
> It's actually not the DLL I want to obfuscate, it's one of the Managed game files, just deleted a bunch of unnecessary and it worked

Great that problem is solved, I will bump to the new version soon also, probably the file you tried to obfuscate was an ELF file for Linux OS and not a PE.

**Comment by sunnamed434** [comment]
Very strange, after moving all files to another directory and deleting the same libraries in the working directory it works!

**Comment by sunnamed434** [comment]
So, I made big changes in new version of BitMono, probably this problem will never happen again, so let this issue be alive for a while
