### ISSUE TITLE
Broken dll after obfuscation with BitDotNet

### ISSUE THREAD

**Issue by wanderer2637** [sunnamed434/BitMono#47]
Hello! I'm trying to use your obfuscator to obfuscate a DLL.
DLL was compiled with .NET Framework 4.7.1 and has only two dependencies:  UnityEditor.CoreModule.dll and UnityEngine.CoreModule.dll.
The dll contains one class and one empty method.

I only use the BitDotNet function, which, as I understand it, should obfuscate the dll so that it looks like a C++ DLL.
But after obfuscation, I cannot use the class from this dll in Unity - there is no access to it, i.e. I can not see it.
Also, I can't add this DLL as a dependency to the project - visual studio throws an error and doesn't add the dependency.
I don't get any errors on obfuscation.

I have tried several versions of your obfuscator but have not been successful.
Perhaps I am doing something wrong.
I want to be able to access the classes and methods of the DLL after obfuscation.
Thank you in advance for your help!

**Comment by wanderer2637** [comment]
> Are you trying to obfuscate an already obfuscated dll?

No, the source dll is not obfuscated.
It's just a compiled dll.

**Comment by sunnamed434** [comment]
Hey!

This is a bad practice to try to reference obfuscated .DLL in IDE (i.e Visual Studio) in production, so let's start from that -
You're not able to reference obfuscated .DLL perhaps any obfuscated .DLL will result in the same issue as you have now.

## What can I suggest to you:
Obfuscate only the file which is running so if you're developing in Unity I guess this is something like your game, so obfuscating Assembly-CSharp.dll is enough, first of all, you need to compile/build your game then obfuscate Assembly-CSharp.dll and only after that you can deploy your game to somewhere eg Steam, etc.
To be clear, obfuscate only your executable .DLL, smth like the startup point which is nowhere depends and references.

Let me know if you still need help

**Comment by wanderer2637** [comment]
> Hey!
> 
> This is a bad practice to try to reference obfuscated .DLL in IDE (i.e Visual Studio) in production, so let's start from that - You're not able to reference obfuscated .DLL perhaps any obfuscated .DLL will result in the same issue as you have now.
> 
> ## What can I suggest to you:
> Obfuscate only the file which is running so if you're developing in Unity I guess this is something like your game, so obfuscating Assembly-CSharp.dll is enough, first of all, you need to compile/build your game then obfuscate Assembly-CSharp.dll and only after that you can deploy your game to somewhere eg Steam, etc. To be clear, obfuscate only your executable .DLL, smth like the startup point which is nowhere depends and references.
> 
> Let me know the results

I want to obfuscate not a compiled game, but a part of an Editor plugin that runs directly in the Unity Editor.
Therefore, I would like to use methods from this DLL, perhaps using code like this:       
       
```
[NativeMethod(Name = "TransformStreamHandleBindings::GetLocalScaleInternal", IsFreeFunction = true, HasExplicitThis = true, IsThreadSafe = true)]
private extern Vector3 GetLocalScaleInternal(ref AnimationStream stream);
```

**Comment by sunnamed434** [comment]
> > Hey!
> > This is a bad practice to try to reference obfuscated .DLL in IDE (i.e Visual Studio) in production, so let's start from that - You're not able to reference obfuscated .DLL perhaps any obfuscated .DLL will result in the same issue as you have now.
> > ## What can I suggest to you:
> > Obfuscate only the file which is running so if you're developing in Unity I guess this is something like your game, so obfuscating Assembly-CSharp.dll is enough, first of all, you need to compile/build your game then obfuscate Assembly-CSharp.dll and only after that you can deploy your game to somewhere eg Steam, etc. To be clear, obfuscate only your executable .DLL, smth like the startup point which is nowhere depends and references.
> > Let me know the results
> 
> I want to obfuscate not a compiled game, but a part of an Editor plugin that runs directly in the Unity Editor. Therefore, I would like to use methods from this DLL, perhaps using code like this:
> 
> ```
> [NativeMethod(Name = "TransformStreamHandleBindings::GetLocalScaleInternal", IsFreeFunction = true, HasExplicitThis = true, IsThreadSafe = true)]
> private extern Vector3 GetLocalScaleInternal(ref AnimationStream stream);
> ```

Oh, ok, I got you. So and this .DLL is C# or C++, which you're trying to obfuscate and then use in Unity Editor? Because if you're trying to use [NativeMethod] (I don't know what does it do this Attribute, probably something like DllImport I guess) of the managed .DLL this is not possible.

**Comment by sunnamed434** [comment]
> 

```
I only use the BitDotNet function, which, as I understand it, should obfuscate the dll so that it looks like a C++ DLL.
```
.DLL will look like a C++ DLL but still will be the same C# and managed .DLL. I meant in the description of BitMono, looks like a C++ DLL is just broken PE metadata and it just seems to be C++, i.e entanglement of crackers.

**Comment by wanderer2637** [comment]
> > 
> 
> ```
> I only use the BitDotNet function, which, as I understand it, should obfuscate the dll so that it looks like a C++ DLL.
> ```
> 
> .DLL will look like a C++ DLL but still will be the same C# and managed .DLL. I meant in the description of BitMono, looks like a C++ DLL is just broken PE metadata and it just seems to be C++, i.e entanglement of crackers.

Ah, now I understand - due to the fact that there is no metadata, I cannot use this DLL as a reference, but if there was a metadata, then the source code of my dll would be easily decompiled.

**Comment by wanderer2637** [comment]
> > > Hey!
> > > This is a bad practice to try to reference obfuscated .DLL in IDE (i.e Visual Studio) in production, so let's start from that - You're not able to reference obfuscated .DLL perhaps any obfuscated .DLL will result in the same issue as you have now.
> > > ## What can I suggest to you:
> > > Obfuscate only the file which is running so if you're developing in Unity I guess this is something like your game, so obfuscating Assembly-CSharp.dll is enough, first of all, you need to compile/build your game then obfuscate Assembly-CSharp.dll and only after that you can deploy your game to somewhere eg Steam, etc. To be clear, obfuscate only your executable .DLL, smth like the startup point which is nowhere depends and references.
> > > Let me know the results
> > 
> > 
> > I want to obfuscate not a compiled game, but a part of an Editor plugin that runs directly in the Unity Editor. Therefore, I would like to use methods from this DLL, perhaps using code like this:
> > ```
> > [NativeMethod(Name = "TransformStreamHandleBindings::GetLocalScaleInternal", IsFreeFunction = true, HasExplicitThis = true, IsThreadSafe = true)]
> > private extern Vector3 GetLocalScaleInternal(ref AnimationStream stream);
> > ```
> 
> Oh, ok, I got you. So and this .DLL is C# or C++, which you're trying to obfuscate and then use in Unity Editor? Because if you're trying to use [NativeMethod] (I don't know what does it do this Attribute, probably something like DllImport I guess) of the managed .DLL this is not possible.

Yes you are right. I am creating a DLL in C# and I want to use it in a Unity Editor.
Apparently, it is managed DLL, but I'm not very versed in these things.
Is there any way to call the methods of an obfuscated dll if it doesn't have a metadata?

**Comment by sunnamed434** [comment]
> > > > Hey!
> > > > This is a bad practice to try to reference obfuscated .DLL in IDE (i.e Visual Studio) in production, so let's start from that - You're not able to reference obfuscated .DLL perhaps any obfuscated .DLL will result in the same issue as you have now.
> > > > ## What can I suggest to you:
> > > > Obfuscate only the file which is running so if you're developing in Unity I guess this is something like your game, so obfuscating Assembly-CSharp.dll is enough, first of all, you need to compile/build your game then obfuscate Assembly-CSharp.dll and only after that you can deploy your game to somewhere eg Steam, etc. To be clear, obfuscate only your executable .DLL, smth like the startup point which is nowhere depends and references.
> > > > Let me know the results
> > > 
> > > 
> > > I want to obfuscate not a compiled game, but a part of an Editor plugin that runs directly in the Unity Editor. Therefore, I would like to use methods from this DLL, perhaps using code like this:
> > > ```
> > > [NativeMethod(Name = "TransformStreamHandleBindings::GetLocalScaleInternal", IsFreeFunction = true, HasExplicitThis = true, IsThreadSafe = true)]
> > > private extern Vector3 GetLocalScaleInternal(ref AnimationStream stream);
> > > ```
> > 
> > 
> > Oh, ok, I got you. So and this .DLL is C# or C++, which you're trying to obfuscate and then use in Unity Editor? Because if you're trying to use [NativeMethod] (I don't know what does it do this Attribute, probably something like DllImport I guess) of the managed .DLL this is not possible.
> 
> Yes you are right. I am creating a DLL in C# and I want to use it in a Unity Editor. Apparently, it is managed DLL, but I'm not very versed in these things. Is there any way to call the methods of an obfuscated dll if it doesn't have a metadata?

Probably if you can make some changes where I don't have enough complex knowledge and only googling is the help. This is impossible to call methods of an obfuscated dll when it doesn't have metadata - IDEs and Unity could think that this is not a PE file format and just will skip it (or simply even ignore it). Probably you can try to do something like that, but you have to at least load this .DLL with Assembly.Load then get your type for example typeof(SomeType).Module.ResolveMethod(token) then invoke it.

**Comment by wanderer2637** [comment]
> Probably if you can make some changes where I don't have enough complex knowledge and only googling is the help. This is impossible to call methods of an obfuscated dll when it doesn't have metadata - IDEs and Unity could think that this is not a PE file format and just will skip it (or simply even ignore it). Probably you can try to do something like that, but you have to at least load this .DLL with Assembly.Load then get your type for example typeof(SomeType).Module.ResolveMethod(token) then invoke it.

Unfortunately, Assembly.Load didn't work. I am getting two errors:

```
Could not load image c:\dll.dll due to Invalid PE header watermark
Run the peverify utility against this for more information.
```
```
BadImageFormatException: Invalid Image c:\dll.dll
```

**Comment by wanderer2637** [comment]
Most likely, nothing can be done in this case.
In any case, thanks for the help!

**Comment by sunnamed434** [comment]
> > Probably if you can make some changes where I don't have enough complex knowledge and only googling is the help. This is impossible to call methods of an obfuscated dll when it doesn't have metadata - IDEs and Unity could think that this is not a PE file format and just will skip it (or simply even ignore it). Probably you can try to do something like that, but you have to at least load this .DLL with Assembly.Load then get your type for example typeof(SomeType).Module.ResolveMethod(token) then invoke it.
> 
> Unfortunately, Assembly.Load didn't work. I am getting two errors:
> 
> ```
> Could not load image c:\dll.dll due to Invalid PE header watermark
> Run the peverify utility against this for more information.
> ```
> 
> ```
> BadImageFormatException: Invalid Image c:\dll.dll
> ```

If you're not able to do typeof(SomeTypeInAssembly) this is meaningless, what Unity version do you use?

**Comment by sunnamed434** [comment]
There's a small workaround with it, make a copy of non obfuscated file and use it whatever you want, add as new reference, etc, and make another copy of the same file and obfuscate it, after obfuscation remove the first original copy (for example from release folder) and paste obfuscated one
