### ISSUE TITLE
README mistake

### ISSUE THREAD

**Issue by Gibsol** [sunnamed434/BitMono#51]
In the first paragraph of README.md, the word "latest" in the last sentence is spelled incorrectly.

**Comment by sunnamed434** [comment]
What you can suggest in that case?

**Comment by sunnamed434** [comment]
If you'd like you could contribute and fix it yourself

**Comment by Gibsol** [comment]
Okay. I can also polish some grammar mistakes in it if you wish.

**Comment by sunnamed434** [comment]
Sure, I'm not wishing but if you have if there is time and opportunity you could do it and I appreciate any contribution and help!
