### ISSUE TITLE
Do command line arguments instead.

### ISSUE THREAD

**Issue by AlizerUncaged** [sunnamed434/BitMono#82]
### Implementation PR

37416d102836e973cf1005f0ed2f235d16600b9a

### Summary

Add command line options to put the file, so I can toolchain this via a bat file.

### Basic Example

BitMono.CLI.exe --executable "C:/e.exe"

### Drawbacks

None

### Unresolved questions

None

**Comment by sunnamed434** [comment]
Great idea, added in TODO.
